apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: actions-runner-controller
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/main/kubernetes/apps/actions-runner/controller
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: actions-runner-large
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/main/kubernetes/apps/actions-runner/large
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster
