clusterName: main
talosVersion: v1.5.5
kubernetesVersion: v1.28.4
endpoint: https://${VIP}:6443
allowSchedulingOnControlPlanes: false
additionalMachineCertSans:
    - ENC[AES256_GCM,data:TdI9TFBW,iv:yml44RduS/hdxKv/geZJXBgmIRoY4Ty9uvAvTKVpL4o=,tag:oIb7shgBIyvXweVMqErgig==,type:str]
additionalApiServerCertSans:
    - ENC[AES256_GCM,data:RxE+aRwH,iv:maIVap/7EdbQK7K6EYkHcKkthKoNdRm8N2Zj4wHPVXE=,tag:jLXE6zg9lj8eU/oxnLXfoA==,type:str]
# Warning: Also used in Cilium CNI values!
clusterPodNets:
    - 172.16.0.0/16
clusterSvcNets:
    - 172.17.0.0/16
cniConfig:
    name: none
patches:
    - '@./patches/all.json'
nodes:
    - hostname: k8s-control-1
      ipAddress: ${MASTER1IP}
      controlPlane: true
      installDiskSelector:
        size: <= 1TB
      networkInterfaces:
        # suffix is the adapter mac adres.
        - interface: enxd83add59cce3
          addresses:
            - ${MASTER1IP}/24
          routes:
            - network: 0.0.0.0/0
              gateway: ${GATEWAY}
          vip:
            ip: ${VIP}
    - hostname: k8s-control-2
      ipAddress: ${MASTER2IP}
      controlPlane: true
      installDiskSelector:
        size: <= 1TB
      networkInterfaces:
        # suffix is the adapter mac adres.
        - interface: enxd83add598b01
          addresses:
            - ${MASTER2IP}/24
          routes:
            - network: 0.0.0.0/0
              gateway: ${GATEWAY}
          vip:
            ip: ${VIP}
    - hostname: k8s-control-3
      ipAddress: ${MASTER3IP}
      controlPlane: true
      installDiskSelector:
        size: <= 1TB
      networkInterfaces:
        # suffix is the adapter mac adres.
        - interface: enxd83add59cc24
          addresses:
            - ${MASTER3IP}/24
          routes:
            - network: 0.0.0.0/0
              gateway: ${GATEWAY}
          vip:
            ip: ${VIP}
    - hostname: k8s-worker-1
      ipAddress: 192.168.10.111
      installDiskSelector:
        size: <= 600GB
controlPlane:
    patches:
        - '@./patches/controlplane.json'
        - '@./patches/sopssecret.yaml'
        - '@./patches/kubePrism.json'
        # schematic:
        #     customization:
        #         # Required when not using enx* mac adress above in networkInterfaces
        #         # extraKernelArgs:
        #         #    - net.ifnames=0
        #         systemExtensions:
        #             officialExtensions:
        #                 # Enable where needed
        #                 # - siderolabs/amd-ucode
        #                 # - siderolabs/bnx2-bnx2x
        #                 # - siderolabs/i915-ucode
        #                 # - siderolabs/intel-ucode
        #                 # - siderolabs/qemu-guest-agent
worker:
    patches:
        - '@./patches/worker.json'
        - '@./patches/kubePrism.json'
        # - '@./patches/nvidia.json'
    schematic:
        customization:
            systemExtensions:
                officialExtensions:
                    # Enable where needed
                    # - siderolabs/amd-ucode
                    # - siderolabs/bnx2-bnx2x
                    - siderolabs/iscsi-tools
                    - siderolabs/qemu-guest-agent
                    # - siderolabs/drbd
                    # - siderolabs/gasket-driver
                    # - siderolabs/i915-ucode
                    # - siderolabs/intel-ucode
                    # - siderolabs/thunderbolt
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uzy27yg04slm0t4naapemy207fd7uh4lda70dxnh932e5dd8n55skgcdrq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBReXZxdjdMRndqUWtwOElH
            dklmUVgwVnBrRjUvd0lBTDQ3QjdLRDExYkM4CmFSVmM4VHVqTVN5aENFczAvYm5R
            aEZENkNZRUVISVZHaHdPUVVjQllSeEkKLS0tIHljRUNSaVNSbGpKb2dVd2lLZ09W
            Z3ppREt2TDdSeHNIYXFBcW0xV2J1cEEKIuxC8oXRprPv74ZEiFgxsK57V7yhCmvn
            vcvE0QsFvXytRzy9D9M/7c9GJ11bIqieAkamtjvlLJE3BcChY8Lv/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-10T21:11:28Z"
    mac: ENC[AES256_GCM,data:7HlW3Yuf1hPaH5nMmOT43XnBHzvAqTLErFX+yOOunTPo8e/BQNs0Sn+QlniBbZhyGWJdR3zPoKTy4hw0rzuamQIlkY2gQnd109vB4MCF58Fh/oNmRoGe2BRHTPO9HQfmNaSbezrfJ21zGMnmdirXnA8J2AlyWH3B9w+B8fHsQEc=,iv:8pbo304xuOQJv9CwC2dQUPScirGoSQ2wOjiccz06Fy4=,tag:u6aVgzjEMWSzgbQuMk8RZA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.8.1
