# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/upgrade.cattle.io/plan_v1.json
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: talos-base
spec:
  version: ${TALOS_VERSION}
  serviceAccountName: system-upgrade
  secrets:
    - name: talos
      path: /var/run/secrets/talos.dev
      ignoreUpdates: true
  concurrency: 1
  exclusive: true
  nodeSelector:
    matchExpressions:
      - key: feature.node.kubernetes.io/system-os_release.ID
        operator: In
        values: ["talos"]
      - key: feature.node.kubernetes.io/system-os_release.VERSION_ID
        operator: NotIn
        values: ["${TALOS_VERSION}"]
      # - key: extensions.talos.dev/schematic
      #   operator: In
      #   values: ["376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba"]
  tolerations:
    - key: CriticalAddonsOnly
      operator: Exists
  prepare: &prepare
    image: ghcr.io/siderolabs/talosctl:${TALOS_VERSION}
    envs:
      - name: NODE_IP
        valueFrom:
          fieldRef:
            fieldPath: status.hostIP
    args:
      - --nodes=$(NODE_IP)
      - health
      - --server=false
  upgrade:
    <<: *prepare
    args:
      - --nodes=$(NODE_IP)
      - upgrade
      - --image=factory.talos.dev/installer/${TALOS_SCHEMATIC_ID_BASE}:$(SYSTEM_UPGRADE_PLAN_LATEST_VERSION)
      - --preserve=true
      - --wait=false
      - --force