---
# yaml-language-server: $schema=https://kubernetes-schemas.zinn.ca/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flaresolverr
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: flaresolverr
      version: 14.0.5
      sourceRef:
        kind: HelmRepository
        name: truechartsoci
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    credentials:
      s3:
        type: s3
        url: "${S3URL}"
        bucket: "${S3PREFIX}-flaresolverr"
        accessKey: "${S3ID}"
        secretKey: "${S3KEY}"
        encrKey: "${S3KEY}"

    persistence:
      config:
        volsync:
          - name: b2
            type: restic
            credentials: s3
            dest:

              capacity: "100Gi"

              accessModes:
                - ReadWriteOnce
              enabled: true
            src:
              enabled: true
      backup:
        enabled: true
        existingClaim: media-backups-pvc
        mountPath: /config/Backups
        readOnly: false
