apiVersion: v1
kind: Secret
metadata:
    creationTimestamp: null
    name: deploy-key
    namespace: flux-system
data:
    identity: ENC[AES256_GCM,data:QfMKZE2+gNJ9J3GUtwfVGXW4fS/iU9dFSxWHZhnu2JfTDVdrN1xOVWDqFT/xA29XxrGvVcHFphGBANF8TteBo2HitTiaYJXzcE1yIfzcH5Tb2b1TXQVTccEVOTeUIGILKDjZVHScucr/9ehyA94rt3xYyzOIkaifngKKRZpwCr3+YgJQ+2rg60d6qn2Q6o8qcWir6ye9gnIohpoREnj2mSdCV1F5zVVO/fUswLKpwaivjBxhv3ogDDkZlh00oeAWz9qdKbz2HjSxZ6rAt/ccaFOXc+gwAtb4wAzkdZdI6tbE7H+FV4FnIbkRn8hh33tbRPW47cp8R6Y4UFPpiiy4Xd83ohyDpi8rwb6ieHJStB4nZOmCRVMenFOpvJvB4q9a4yPb6YsEJn/BGiNEn69eP1XlU3dsv6S/BMTR1V54kLQCfXy0FUPr+2YqAVizWk+BcGi5zki8/9o0ohNVIP4c7zDXLT9ga4a6r7ifQV6kfdjQOQhlGjHv2aBYN8mMXkPzgC1mOF/tLKaxbbi8eIge5IClFJPZP0kb,iv:KX1Lb2qrsTI4W5iT1M7DQlR929FWoW2jgzBVH45mUf8=,tag:kRU1Zr+ufdLnXi6di2rZGA==,type:str]
    identity.pub: ENC[AES256_GCM,data:c9oAXm4xU6B5dFBVnYfs59A62cPosZM3Zb4K/R4t4caFlRA03fYKV1B+VpOMk8aFM6aKdj9tMrT3JY4iLW2ZB8GK5hagelpm3SH18Gm9UR8Nqz79keZdPjcq8PD+SjwJwkLLlDLFR91uZgKxRuJJ97BdqpMiSiYj2KpuYP8DwAb4lWxSGmjme4oV+A8AFcl97WTkwGFDSVQ9JMzOCJ7W76XMeHlBRotfrc8JuJSnrTGukqtULtjB0ilsntNbAxeNGBvIa1oNC3VrEUn0WZ2IjEcNhqXIGr2CxzktdZDlShmDf4eKY6tS9QT0+UvRWOFhvWpm+jIVapOFDhj9yto5xa70rrspKjQizvzMNCY8V4DHlapw,iv:rmS7D7HGSVzQRLs61eLQvI2B4qlhbItdqsFCsOGOoP8=,tag:Knp6LOEon2H5kbfOcpnzYA==,type:str]
    known_hosts: ENC[AES256_GCM,data:oNv9lHCwDPKHRQ+6VWCqwDS/hPoOhjFLJZWwziki6QnyvmBaQaek/b92HSu7AkdChk0m2x5/eE16gH2gGC+MC6Ac+/FuQBuiJX85wKgjWVgHwoCqsMHUTH4ccY14g6A7dAHfLAFZak0zkY77op+3qWFSyCeNU8+eWmrwj27yznEJMDaOMWMOTw7Aci/c2KYQFt4/6JNPUYntTuQ7iylxe9EhYiqgCD1FJG0U33VsX3ojVqvNE6S2UfrVnWP7rtUmMgG9ZZI3xJRtJXlNhsCJQRR3unxyCin4w3G8JzAqNOqiPL77,iv:qVq0x2Xq2aEVaN00yEYlbe020AxM8blvpJ6bIYGSqjo=,tag:YFc7XSYJHcnBLq2Gs2iRPQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uzy27yg04slm0t4naapemy207fd7uh4lda70dxnh932e5dd8n55skgcdrq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZM2xLOS9QL21kb0lzYkc2
            RTRBK2VlZHg4cnYyNFJhWWtyV294K2NWcGdzCmpZWkJWbW56anI2cEJEbi82YXZn
            QUNma3QwUlVrTGxuZzdtQStudHdVMDgKLS0tIERGZXp3djV5R3ozNThkaHE4YTF2
            Sy9Wd2J6aWttV3Z2NUZQbjVkREE2cWcKj/3pIW3BlgzNCqbRi2q8Ben1Phn5PUMS
            5b+eqa6bOfmkRGheIxasxE6YqaVT/5xpAXmS2UqUwQUXQzUDP+sL+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-02T19:44:06Z"
    mac: ENC[AES256_GCM,data:udgZMoz4grrR2A8c/AcQ+oFGRN70eJKu+ll7UH9H592wwZJNG5jHz6OEE3J6rBvVr3nZ9U99/Lss60FnDzO/gd1w7NDH/u41fGEF1C+ZNLxGItUQCr8aBVM5yJQbGYXZly0mMbRtHCenlB3m34GZW3J84jAQkRWefaqSn9Ep6Ns=,iv:L2PfFZ29XK3sIWgJaHSDvQaM9nt/FV1jrlVfjCjmBp4=,tag:QoEe+0AVI1igz30o/BJ1IQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.8.1
