metadata:
    creationTimestamp: null
    name: deploy-key
    namespace: flux-system
stringData:
    identity.pub: ENC[AES256_GCM,data:3IAmGWDQgzYnyLfLfyuwn1W40qNkprYQrMN/00BxKrY8vEVssYElQaYUuzeEtVotLqjUu3U+1MCfoqXKTMhZgisrDlxjbHwlAoMaEU1IHRy8bY+wIqcP23uU935OVODGHu7su8uKo++ux6KRuEMkZOFQnzICOTQiPKfJZ7KBsHG8NpeCGjEZplr/uu+jUDqmM9A/ybB03i8JQZkE9d1l8GWPcL/uI9DFepxl5pjJdAHPx9VqpQ/FRWRBxlN9HqQeonziuGyq2GNM/RyyD984oQhAtgqV0wg=,iv:cSWU1dGv2AkxcdJKv2YMgjigaXbOnxnt1gZbZz4J5kk=,tag:QCzVg4aMHBxEFAw+2hGzlA==,type:str]
    known_hosts: ENC[AES256_GCM,data:pZtWUifS++EnAipQw/GuzHXemMjJhefy0MnlESU5OkFuOvy+Zd0XN6+IxVxDtZ+3p/WhJsZe4YIFDKpD9BgIPVgycSLOllNRAkPQ9+cPenkWsc+vSYyHkDSbQ+xV3EvI78U21OuKmMF/WDY+vpSYbyyjt/tYSq3Dil+wexFSzarV+Xgz40bH3MKw0i//sQc77f1egibCg6HHsM+IuzdagWYgz/xnmuPYqrDO,iv:jhI498GNz7PEPjIomXNml8mWQf3eHG7xowydg/DQFAo=,tag:iV3x+Xeg/5i/VQ5lRCL81g==,type:str]
    private.key: ENC[AES256_GCM,data:yyWZ7C64Bk6Bz6BIpds7UtMR3nMAjYGcbTXsE7YH/ze2VQwk9IdCe214D62UtSXyx8q4zpNRaPyXTQXAbeKe4ShNNThGVMHDHQQx3ivgAaZJOh4FFLw5XAAZBZwK4vyq0mytOpATSQmwYQWBTHwaqP4y6rmLwb2MmpTez1KcBdeMOlAyt+R9na0VdLn+5kBoMcD7/ptLgcPE5cnxu+F7+2BlNTmmOu0RqsEC97KHwAIUlje4pjFJuM5HUCA0YdEXQN+cNyayqB4PFi+9QVOk6YgxulCpV2sFiTDsdBBBvbif8c0O2TtbanDaT92FV/4fORcFE+YGioWAC+P+zvig3ekNoA0HT12iOeOVQvkNgC8bFd5IwiaiwTdeBdmPkBQ98fyCSNXt,iv:ksj9cS+KaqZ2MlHb4BUClC9klUcPjEj80uEAqpFRGNQ=,tag:RJX7pB6HYccIYav4auG3JQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uzy27yg04slm0t4naapemy207fd7uh4lda70dxnh932e5dd8n55skgcdrq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFUDRLbkx3anVMZVNBeGh1
            dW9zNXJleVRvMHBGbHgxYWZteTBBdUl3OWlRCnk5TjVDc29tcDAzbzJ2TUR3WThR
            bEI5dU5PaTVwSEVHRGxEOGZjazFzK2cKLS0tIHg4b3NLbVdTelg5TlZIUHZOeDR4
            VkFjdW9BVlZYeGNWcUl4WWo5SVkyMUUKJvuX0FnYth6UbqpVFzrNj0xnHkJm5sd/
            chw6Bock0z8gL2wkQLQoYr8epSRw4JIMxwTu0f6K4D6/NXEiccF0iQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-18T08:29:54Z"
    mac: ENC[AES256_GCM,data:ijDmIJTh7M+n8k7eTd4QIRbpT6t6LTko+w17AQ4k/fTI51wbHmNN1XV+fMmBbK5TdSNNyh+e+Oha9E/TW0Tf5OHQ6l54ecYEZjW8MBFcR1uf8sUmIYXSsentWcmPsa97KB20NqCobViTO1dpVLi7rYv3JNC8tRc7ZDUMsQwn/X8=,iv:CLlcC9SsUplNVyGI2cd83xZs4JiXpqANRwdSNsDaGi0=,tag:/45soIVkLBdCZ7pkmer4Fg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.8.1
