apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
data:
    identity: ENC[AES256_GCM,data:lCWSB/XOy+IL4N2yLGvLhYjDno6Pd+A9PyO8B6RGFfufhMRMShpPiCdjWunSmSfND438eSjEt19naQa/gJWzBQ3EyesGSqqYUpqwJfrb3oOybNY203dMMaZ3PFmHeULJJbbQ/Q1/wbsdIJai2HQ+2fEtx5mGwSZSrsyznow0yCt/hxyH4EpoLhQYnsaylJk6xfq3MG/5+GsNhu42292nymD/jUQxYIzFdc4seZwvKs2x2MNIZulfFE+8TsSgtqs8CAF7OPcYlU6q7dYSlWVv4hvLcsXO3uUL4fMne8i38j5Cwj6uH/kBcMIeys8d6C5Qnt1booJvHiGq+rL74OHqbrdCjcxfQQT8CDU9Z57E7XHsAYueYBKFfbjaS0czCI7s/mao3PkYh/uOeNjnPpPxrZNaiPaaR7ltBLYdorNvopFX3aertcQF7dvuuMAMXnCuOe9NvVQ5LD/0PxsFriTe32ck/qa3Vhw/HkUD4F3u2alzQlY3kwm1/J0Dcq6znac+Oal2jQbqUphNl4BUNRWT0sHuJDBK9KbB,iv:9ikcoJja9wLPmX8tAOgipRhFXV45COMjWL0T8CMJeiU=,tag:LJcMv7o6bNwLIRUbvoSlPg==,type:str]
    identity.pub: ENC[AES256_GCM,data:QUPMh7WmXP3R8YeLsIhctPaDv6friGOm0k9DTZWpFkpMespMaiZjIETdnKAjR9d2mFOTgLGhjJAhfx1b6X1+XS0hQ5no3d+Db2vbnFX1P1P0ETAA5UTssDtBMtvgx4z0PPNgAmfFIM12cNXDQolD9feRew4u6U/T3fJowQAXYj4MlFZVKwq/9XznIFkO3nd51k237U9uQrrD5DdUYpeBlurPlA/G6Aj9Z/dKJB1oD4c9/yIu/5CFpnDszhITgxgsF/t7iUC6E3N0hfMZgubgyzDcxKqt5uFjUVxmFtZ5yP0NlusHPzg2HLGU6KxbqpRCxnnOEmJwvuBlmUxr5D/tx9CiYWFMCJHZqGv99u1Ck2umgM3t,iv:APj2v71Fawad9WKGoQiTj6SdRXxpazGWJUdI8zjVLKY=,tag:SVGNr+dMwF9LbxhVY9nQjA==,type:str]
    known_hosts: ENC[AES256_GCM,data:5cjXECWzwViXiJd5yWVzuiuKo9ZO6/RIFm1fUA8HGObOmQ1Bt7JNnoa4+MBA2FdGQYbaZ7Nl1IepecKzEf+dkU8fW2+QCAVrTh3zuX1e8LjzU2q82GiBXZzLVxW+mVcjDCw6G902KGS1GFaYE6PZpZ8Jq+6zLyE7cu1w6+6N55ONK1ReadfgPTDiskHxvQUcemA9MwqLrZmVKI8VxBc6FwR/qGXwaKywSUc3pnmQyRq6VFigpn0XjywrR3HJZ6vu2MyZmMCFSFqsZKxbu04ybiHhaN/AQG2cO2liYjZp48etnqlS,iv:d9TRrGyNd7l42I38he0cO8zLskZCXb9/F0k2xzZi1AU=,tag:Sb6YkYXXA02uMP9BzbRCRg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uzy27yg04slm0t4naapemy207fd7uh4lda70dxnh932e5dd8n55skgcdrq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiNEZBYTNIVVVvUXhIMUgv
            MitQL3pyV1EyQ0ZvSGx5cG56WTZqSnl2enp3ClhUYlZOeFhoNkoxVVdZM0ZLK0N6
            MDYxanZDQ28xRjVIV2g4TlpRL1llb00KLS0tIENzSER4TDIrMjUwZmlDS1VpbERR
            MThIQ3ZiR0lOcHV5cEhaZUxzdTBoYk0KhKwuSFKO8R+WROy3V523xVfPY5ZL1hMw
            DOdjpWdis/R9BrzuU5CRWTxSiWZXLU66U2Wv5Mdcy57j+bMfIuONrw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-08T20:06:19Z"
    mac: ENC[AES256_GCM,data:gQz3zBfXuPjGEnK4oWnNNLxP2RhHFiAw+efkpoSl3mcnshnWkGhJhPk1ca2MRs/fsMOnc1eFSer64VaB6Lflp8pxH2VUnO8/XX4OWaACkyqLCwwDO/6hDlyo0hIH+odv36iNyJriJMkiRk3zYKs5oIso7R4VdZ0e6cE4WCf53SI=,iv:1XSu/OFt7ce5jZgZR8RrkM/VrONitmQHxLHefkkxeB4=,tag:itef3M3ldPUgo5qjcSloyg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.8.1
