apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - grafana-agent-operator/install.yaml
    - cert-manager/install.yaml
    - metallb/install.yaml
    - rook-ceph/install.yaml
    - cloudnative-pg/install.yaml
    - intel-device-plugin-operator/install.yaml
    - openebs/install.yaml
