---
# yaml-language-server: $schema=https://kubernetes-schemas.zinn.ca/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: blocky
  namespace: blocky
spec:
  interval: 15m
  chart:
    spec:
      chart: blocky
      version: 14.5.0
      sourceRef:
        kind: HelmRepository
        name: truechartsoci
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:

    service:
      dns:
        externalTrafficPolicy: Local
        loadBalancerIP: ${BLOCKY_IP}
        type: LoadBalancer
    customDNS:
      mapping:
        - domain: schouten-lebbing.nl
          dnsserver: 192.168.10.202
    caching:
      minTime: 15m
      maxTime: "0"
      maxItemsCount: 0
      prefetching: true
      prefetchExpires: 12h
      prefetchThreshold: 5
      prefetchMaxItemsCount: 0
      cacheTimeNegative: 30m
    # -- set blocking settings using Lists
    # Primarily designed for inclusion in the TrueNAS SCALE GUI
    blocking:
      # -- Sets the blocktype
      blockType: nxDomain
      # -- Sets the block ttl
      blockTTL: 6h
      # -- Sets the block refreshPeriod
      refreshPeriod: 4h
      # -- Sets the block download timeout
      downloadTimeout: 60s
      # -- Sets the block download attempt count
      downloadAttempts: 3
      # -- Sets the block download cooldown
      downloadCooldown: 2s
      # -- Set the start strategy (blocking | failOnError | fast)
      startStrategy: blocking
      # -- Sets how many list-groups can be processed at the same time
      processingConcurrency: 4
      # --  Add blocky whitelists
      whitelist:
      - name: ads
        lists:
          - https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/optional-list.txt
          - https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt
          - https://raw.githubusercontent.com/rahilpathan/pihole-whitelist/main/1.LowWL.txt

      # -- Blocky blacklists
      blacklist:
        - name: ads
          lists:
            - https://big.oisd.nl
            - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
            - https://raw.githubusercontent.com/PolishFiltersTeam/KADhosts/master/KADhosts.txt
            - https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Spam/hosts
            - https://v.firebog.net/hosts/static/w3kbl.txt
            - https://adaway.org/hosts.txt
            - https://v.firebog.net/hosts/AdguardDNS.txt
            - https://v.firebog.net/hosts/Admiral.txt
            - https://raw.githubusercontent.com/anudeepND/blacklist/master/adservers.txt
            - https://v.firebog.net/hosts/Easylist.txt
            - https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext
            - https://raw.githubusercontent.com/FadeMind/hosts.extras/master/UncheckyAds/hosts
            - https://raw.githubusercontent.com/bigdargon/hostsVN/master/hosts
            - https://v.firebog.net/hosts/Easyprivacy.txt
            - https://v.firebog.net/hosts/Prigent-Ads.txt
            - https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.2o7Net/hosts
            - https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt
            - https://hostfiles.frogeye.fr/firstparty-trackers-hosts.txt
            - https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareHosts.txt
            - https://osint.digitalside.it/Threat-Intel/lists/latestdomains.txt
            - https://v.firebog.net/hosts/Prigent-Crypto.txt
            - https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Risk/hosts
            - https://bitbucket.org/ethanr/dns-blacklists/raw/8575c9f96e5b4a1308f2f12394abd86d0927a4a0/bad_lists/Mandiant_APT1_Report_Appendix_D.txt
            - https://phishing.army/download/phishing_army_blocklist_extended.txt
            - https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-malware.txt
            - https://v.firebog.net/hosts/RPiList-Malware.txt
            - https://v.firebog.net/hosts/RPiList-Phishing.txt
            - https://raw.githubusercontent.com/Spam404/lists/master/main-blacklist.txt
            - https://raw.githubusercontent.com/AssoEchap/stalkerware-indicators/master/generated/hosts
            - https://urlhaus.abuse.ch/downloads/hostfile/

      # -- Blocky clientGroupsBlock
      clientGroupsBlock:
        - name: default
          groups:
            - ads
    k8sgateway:
      # -- list of processed domains
      domains:
      - domain: "truecharts.org"
        # -- Optional configuration option for DNS01 challenge that will redirect all acme
        # challenge requests to external cloud domain (e.g. managed by cert-manager)
        # See: https://cert-manager.io/docs/configuration/acme/dns01/
        dnsChallenge:
          enabled: false
          domain: dns01.clouddns.com
      - domain: "kjeldschouten.nl"
        # -- Optional configuration option for DNS01 challenge that will redirect all acme
        # challenge requests to external cloud domain (e.g. managed by cert-manager)
        # See: https://cert-manager.io/docs/configuration/acme/dns01/
        dnsChallenge:
          enabled: false
          domain: dns01.clouddns.com

      forward:
        enabled: false
        primary: tls://1.1.1.1
        secondary: tls://1.0.0.1
        options:
          - name: tls_servername
            value: cloudflare-dns.com
    cnpg:
      main:
        cluster:
          storage:
            storageClass: "openebs-hostpath"
          walStorage:
            storageClass: "openebs-hostpath"
        backups:
          enabled: true
          endpointURL: "${S3URL}"
          provider: s3
          s3:
            bucket: "${S3PREFIX}-cnpg-blocky"
            path: "/"
            accessKey: "${S3ID}"
            secretKey: "${S3KEY}"
        recovery:
          method: object_store
          endpointURL: "${S3URL}"
          provider: s3
          s3:
            bucket: "${S3PREFIX}-cnpg-blocky"
            path: "/"
            accessKey: "${S3ID}"
            secretKey: "${S3KEY}"
