---
# yaml-language-server: $schema=https://kubernetes-schemas.zinn.ca/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: autobrr
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: autobrr
      version: 7.7.0
      sourceRef:
        kind: HelmRepository
        name: truechartsoci
        namespace: flux-system
      interval: 15m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:

    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
          certManager:
            enabled: true
            certificateIssuer: ks-le-prod
        ingressClassName:  ""
        hosts:
          - host: autobrr.${BASE_DOMAIN2}
            paths:
              - path: /
                pathType: Prefix
