---
# yaml-language-server: $schema=https://kubernetes-schemas.zinn.ca/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: hass
  namespace: hass
spec:
  interval: 15m
  chart:
    spec:
      chart: home-assistant
      version: 24.10.5
      sourceRef:
        kind: HelmRepository
        name: truechartsoci
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:

    homeassistant:
      trusted_proxies:
        - 172.16.0.0/16
        - 172.17.0.0/16
    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
            middlewares:
              - name: auth
                namespace: traefik
          certManager:
            enabled: true
            certificateIssuer: ks-le-prod
        hosts:
          - host: hass.${BASE_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
    cnpg:
      main:
        cluster:
          storage:
            storageClass: "openebs-hostpath"
          walStorage:
            storageClass: "openebs-hostpath"
        backups:
          enabled: true
          endpointURL: "${S3URL}"
          provider: s3
          s3:
            bucket: "${S3PREFIX}-cnpg-hass"
            path: "/"
            accessKey: "${S3ID}"
            secretKey: "${S3KEY}"
        recovery:
          method: object_store
          endpointURL: "${S3URL}"
          provider: s3
          s3:
            bucket: "${S3PREFIX}-cnpg-hass"
            path: "/"
            accessKey: "${S3ID}"
            secretKey: "${S3KEY}"
