---
# yaml-language-server: $schema=https://kubernetes-schemas.zinn.ca/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: bitmagnet
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: bitmagnet
      version: 1.3.1
      sourceRef:
        kind: HelmRepository
        name: truechartsoci
        namespace: flux-system
      interval: 15m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
      stopAll: false
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                TMDB_API_KEY: ${TMDB_API_KEY}

    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
          certManager:
            enabled: true
            certificateIssuer: ks-le-prod
        ingressClassName:  ""
        hosts:
          - host: bitmagnet.${BASE_DOMAIN2}
            paths:
              - path: /
                pathType: Prefix
    cnpg:
      main:
        cluster:
          storage:
            storageClass: "openebs-hostpath"
          walStorage:
            storageClass: "openebs-hostpath"
