apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
    name: snapshot-controller
    namespace: system
spec:
    interval: 5m
    chart:
        spec:
            chart: snapshot-controller
            version: 1.0.1
            sourceRef:
                kind: HelmRepository
                name: truechartsoci
                namespace: flux-system
            interval: 5m
    install:
        createNamespace: true
        remediation:
            retries: 3
    upgrade:
      cleanupOnFail: true
      crds: CreateReplace
      remediation:
        strategy: rollback
        retries: 3
    values:
