---
# yaml-language-server: $schema=https://kubernetes-schemas.zinn.ca/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: recyclarr
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: recyclarr
      version: 8.3.0
      sourceRef:
        kind: HelmRepository
        name: truechartsoci
        namespace: flux-system
      interval: 15m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:

    addons:
      # -- The common library supports adding a code-server add-on to access files. It can be configured under this key.
      # @default -- See values.yaml
      codeserver:
        # -- Enable running a code-server container in the pod
        enabled: true

        ingress:
          # -- Enable an ingress for the code-server add-on.
          enabled: true
          integrations:
            traefik:
              enabled: true
            certManager:
              enabled: true
              certificateIssuer: ks-le-prod
          hosts:
            - host: recyclarr.${BASE_DOMAIN2}
              paths:
                - path: /
                  # Ignored if not kubeVersion >= 1.14-0
                  pathType: Prefix
          tls: []
