# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: actions-runner-controller
    namespace: actions-runner
spec:
    interval: 30m
    chart:
        spec:
            chart: gha-runner-scale-set-controller
            version: 0.9.3
            sourceRef:
                kind: HelmRepository
                name: actions-runner-controller-charts
                namespace: flux-system
    install:
        crds: CreateReplace
        remediation:
            retries: 3
    upgrade:
        cleanupOnFail: true
        crds: CreateReplace
        remediation:
            strategy: rollback
            retries: 3
    values:
        fullnameOverride: actions-runner-controller
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uzy27yg04slm0t4naapemy207fd7uh4lda70dxnh932e5dd8n55skgcdrq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPdStGcGdMYnNjK21adlZs
            aG5kOXFnSGMrdFFGOU1mb2ljU0dWRnB6OEFzCnJGWEQvdCtqWHRncnNUYUFvRzhP
            MUFxNEdkdDU2TUd3eFZYeW1mQk1MeFUKLS0tIHRlS2pJQlMwbHlvdVZxeExDSW9N
            aEVjSHB3WVVwNHVnTDJMU09vSkMzTGcKsV2VHzj57wqNcK2RItc9+gNJGZIVfOkA
            hph87Y42lrJyUPjWQ+excsRltUcps6/YinRlAp8d5AWHLuPSzjZ0sw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-23T18:58:19Z"
    mac: ENC[AES256_GCM,data:AhGoXVCriVBI2JypTDUJq/Ri+VsLAHNryG86lfEOS5DMlFaQHHfPqLE39GEtrDO3DeMhc1gftxOy+30gcUn2T6ty73rkBTKmAdyXq3QSSq6VzmbPWx3mSwJ7dNEG3cnJpmRfGHR9jRe36RXiiwaC82c7qZyOS6wRMuT40kn+OSA=,iv:YKc2cR8GEsocpi9GfXOwJGbMCi8qf4TTpsVr0RQr9JI=,tag:GfrXX8e6c9vwv0Yjcz22rQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(github_app_private_key|github_app_installation_id))
    version: 3.8.1
