---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: longhorn
  annotations:
    snapshot.storage.kubernetes.io/is-default-class: "true"
deletionPolicy: Delete
driver: driver.longhorn.io
parameters:
  type: snap