---
# yaml-language-server: $schema=https://kubernetes-schemas.zinn.ca/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 15m
  chart:
    spec:
      chart: traefik
      version: 26.2.1
      sourceRef:
        kind: HelmRepository
        name: truechartsoci
        namespace: flux-system
      interval: 15m
  maxHistory: 3
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    workload:
      main:
        type: DaemonSet
    defaultCertificate: tc-wildcard
    service:
      tcp:
        loadBalancerIP: ${TRAEFIK_IP}
        ports:
          web:
            enabled: true
            port: 80
            protocol: http
            redirectTo: websecure
          websecure:
            enabled: true
            port: 443
            protocol: https
            # -- Configure (Forwarded Headers)[https://doc.traefik.io/traefik/routing/entrypoints/#forwarded-headers] Support
            forwardedHeaders:
              enabled: false
              # -- List of trusted IP and CIDR references
              trustedIPs: []
              # -- Trust all forwarded headers
              insecureMode: false
            # -- Configure (Proxy Protocol Headers)[https://doc.traefik.io/traefik/routing/entrypoints/#proxyprotocol] Support
            proxyProtocol:
              enabled: false
              # -- Only IPs in trustedIPs will lead to remote client address replacement
              trustedIPs: []
              # -- Trust every incoming connection
              insecureMode: false
    ingress:
      main:
        annotations:
          traefik.ingress.kubernetes.io/router.tls: 'true'
        enabled: true
        integrations:
          traefik:
            enabled: true
          certManager:
            enabled: true
            certificateIssuer: ks-le-prod
        ingressClassName:  ""
        hosts:
          - host: traefik.${BASE_DOMAIN2}
            paths:
              - path: /
                pathType: Prefix
