---
# yaml-language-server: $schema=https://kubernetes-schemas.zinn.ca/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: grafana
spec:
  interval: 15m
  chart:
    spec:
      chart: grafana
      version: 14.0.1
      sourceRef:
        kind: HelmRepository
        name: truechartsoci
        namespace: flux-system
      interval: 15m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    workload:
      main:
        replicas: 1
    ingress:
      main:
        annotations:
          traefik.ingress.kubernetes.io/router.tls: 'true'
        enabled: true
        integrations:
          traefik:
            enabled: true
          certManager:
            enabled: true
            certificateIssuer: ks-le-prod
        ingressClassName:  ""
        hosts:
          - host: grafana.${BASE_DOMAIN2}
            paths:
              - path: /
                pathType: Prefix

            PENPOT_REDIS_URI:
              secretKeyRef:
                name: rediscreds
                key: url
