# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: actions-runner-small
    namespace: actions-runner
spec:
    interval: 30m
    chart:
        spec:
            chart: gha-runner-scale-set
            version: 0.9.2
            sourceRef:
                kind: HelmRepository
                name: actions-runner-controller-charts
                namespace: flux-system
    install:
        remediation:
            retries: 3
    upgrade:
        cleanupOnFail: true
        remediation:
            strategy: rollback
            retries: 3
    dependsOn:
        - name: actions-runner-controller
          namespace: actions-runner
    values:
        nameOverride: actions-runner-small
        runnerScaleSetName: actions-runner-small
        minRunners: 1
        maxRunners: 6
        containerMode:
            type: dind
        githubConfigSecret:
            github_app_id: ${ACTION_RUNNER_CONTROLLER_GITHUB_APP_ID}
            github_app_installation_id: ENC[AES256_GCM,data:1EgzhRerf0Y=,iv:d0RtdfxRdeBv6BGuAYl+1KKv/4mZMQhnsubNjTCLL6c=,tag:v7WQAzbE6w7Ee0lLBVLAyA==,type:str]
            github_app_private_key: ENC[AES256_GCM,data:IVK1FsbWkGOSfSYO+7YxQT4e8klbNOG+RXMhGNfrPZ46itCk59Cdbo/jPzBS//hr7vMXw/KTuX6Gauiz0/+GpZjTG5vtsF2gMARgW52+Kc+T+hAFercb7ctBZo3FWjA3TiYMedzDSCag+rYY7jLD39uCwq+0yyPm8hCKYrmu/Rn29kPUfseuzCQiRvgR7sm2aCkmw/HtXqsdQjPweO0MwvldWcCcvSgGTyy9z3rq0od/7lmJS3fXcdFm+TO2uc8BBkdpkv3M+/O8gm4wthXI+VKFDITBRheyxeYwD/f9tpMPU0Lwm3YHweock7F+R/CUKbuKhpmceJF0anvEf8uTm8HJAzU3LwIwHCOiZDBx0e39jL2xkbDsWBIzDS4H0ZcgM+TVZIr6Aw+rDqC+QA7mS7dDFf3hXnpajItlVH0b62v77PDVx2fQ11O2OlQmxnOC1VIWaulFHD/2cf3p1Dx+szZG3MxpCIVNBkwdc47Ew2pHuVTSDVI4Pi7PUrepsHzNjanzaK8kYgr78iN6AWMsyb1d+5lQfYX0Z1+OcfEQqmaeJNpO1E0VTtyvkmvgqlPMy7Ptr+GvfJYCwfIxNGNhoGqa8aF5ELshPB2471P1T9ycwV74OEIRcKv74z1gOgwlxm5xaOFNeQhwiTEfh7ECKevZuTook9og/oJffyKB91X+KcVAtZoR4C6QiJs7cYoH3Qb8hIN5IzuFpRhVZuj1L/9rw6+DQ1TeQZpHyXVDO0cD51wB1Sz/yUeCkWCZPmKRTOulUUdp84HG20685eOoJLfvyVUqR/P2W849ZZpWAf6A4gupTB1wOdawJgO8jdY8eUExL1y+gRvSOrFlgATiPJOGrPWGcIQGuzobjec8JGMcStaSMXr2PYrCWbb+NSkl/wZ7I0qoY0T8CoPEyb96qXdQrLg1cwN7NMRx9OivZYi71mO5fmgy3Gu/xdiXZxZiUvNpvIZbAJ3L9znutsRG1oxZ2pjWGp3xDzUy9+mdDg5N7qa20lEcIiZXd8xUaabEmkCzOu7HuTUC8sZpOPObqxA5hUHQBDKrraHEtv9i2zA0KldHI6rbLYQ+B1L0Be2K+xqKiKt0jiWW/I+up5QBzh1RSaQ+z5Jb+uuFjum6XpDV8tUcYkCrkEqOTX0kIXtOUQ1NhbHC9I6ArBsSKt0vukktQ3fKbhe+/UunJ4f5mm9n3z/WViXfq8efjLKwZePhvrci0CxctnlKpEs3s+sYAQua85mmCCK+9NvEqCbIcQ59LsOJky9vf2Iwy/hywukHU9YDN2UShDtssxHm81M80ihFaikLOc3m5J8oeloTYUcjnSaEjRkDKU7t72g1JQZTlS7Ed5HxXlt/x0CQY+46liPkLGnNUpaX4DPZ16KjISM2MjSqUaovDoqJgiUgHDz8IVrbJfFmR4jZ+Yej2Yh1c6fWushAldw8Wxhv0FWSbd+aCKzmR5BWfJseBL8f0NuBTpCvIH7j3S7ptYzhhytCPzC2e9CL5ng+Kx/BfaIdf+vJUxsXEg46h7bvCLZRx48A7k0Ds+l5hK/rpLpOBo7ZHX1JfqNVdy1DHN6wI/U2CHOmFI2cxhdJju01TemdGx0KrbKWpVWpm5BiemuRhp3lz0/vWjCbwjqUzZZRgXlM+YHoFZskEBa6+9lknUwv2vxC6FZuzEb63ti5UJz8+lP3GdJqVxm1JTs90q7vU+j7MnthcQ6qFBc9UH+75yNYdyvuBXl04wIVly0L2EliJMbDI4Vd45WpoPNZZVrZCkd3UhEzUQhUM1zXw5LOH4enN/n1JmOQtCXeZcJOkziEA4Ij1uu3h1MCbX9sSwZeKctIW3k32KPad2tPREUPQGmZSMbJXJDd8LzclBp+cQMwYYOn/jOHF9Re1RnCcfTpeZR8eV6vsxeFApXCl+M3VZ1uRB9ovty2HO3rXqKEf5rFfeNYDSher6AR8SW3BlwU0jLF7bpaySwXREtA95UuUcYFrFKPWcFviLIBCiQH02BSW8sj3wvf7x44RdzaYz6h/cgsCA9bJ/u2Fv6kho+waB/qQLpwVHJ4YRLBts6Oe6B60aNkYBt4Az6Gz5svSbSq3AUjCv61V6WAs2PToY8991QcRSev20rTiv5HRPA2Kl1LVlKaamoM+EmH97EsY8b8a14klHCoKUN5ayzC9ada4SWXTWPjZke5YhTb2PRNqZFuMraDC0EuQUIS6p7JKRHNoTzenXNIX6b//E4pg98iaw==,iv:cXXpNMpsAaiqfHhxGkqpvmfSB7F+ZUZ30hUFoczyNKY=,tag:qOjNLWVL9rONN8ZLeKSDsA==,type:str]
        githubConfigUrl: https://github.com/truecharts
        controllerServiceAccount:
            name: actions-runner-controller
            namespace: actions-runner
        template:
            spec:
                containers:
                    - name: runner
                      image: ghcr.io/truecharts/charts-ci:latest@sha256:f140cac74f5ed15b985209dbc9b154d92df532599b7f9766cbbf4771fc0db304
                      command:
                        - /home/runner/run.sh
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uzy27yg04slm0t4naapemy207fd7uh4lda70dxnh932e5dd8n55skgcdrq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2TmZkb2R2b1pCN3Zob1E1
            U3ExUWpLMUhuS3A1RkN5aGFEdTJ0SE1aOERVCi9IYTlIOWFKREJ4ekJEWWRDTWtH
            ZG14QUFVbkkyYjNqcllIUzNFcXI0ZG8KLS0tIHZ2SVFZZFJOaTBwYzE2Mm1Ub3Mw
            RmZ4TDI1bnArQ1g0aVBLVjAzblI2encKx9pqNlVRrfUofDWdFsR07OpJm2CcJ90w
            LR1vZeIlIQDuEP3tD3+VwR9Z0t9a5OMyP41OodNDhUHlAbTJtkPxUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-23T19:01:54Z"
    mac: ENC[AES256_GCM,data:hrNm6FKtOgQQ6oiL99JB2BDzJ26L7fB3X+pjLXE86lGYJmETX25ocgOctpgCMe29D2iZkLryij4JCWdObyOTh2jmR4CiV8QmTQis5MPY/jFX+0K0Htdr0XYBEhntM9nx2lWbKw0kEWGQq2CSg1dASCWgCby3PCx+T2xcKr5bEjc=,iv:/o8JO1dvKlM+7AVecfEljxG+k1p7zv9hMaogr8HhiaM=,tag:A7cY/w34Xr4rxm5+JuI+XA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(github_app_private_key|github_app_installation_id))
    version: 3.8.1
